# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20170123_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='submitter',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='link',
            name='rank_score',
        ),
        migrations.AddField(
            model_name='link',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=250, verbose_name='Thumbnail'),
        ),
    ]
